# Generated by Django 2.1.1 on 2018-09-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='accountType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('SuperUser', 'SuperAdmin'), ('User', 'User'), ('Visitor', 'Visitor')], default='Visitor', max_length=20),
        ),
    ]
