# Generated by Django 2.1.1 on 2018-09-28 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20180927_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectNumber', models.CharField(default='H-00001', max_length=20, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('createDate', models.DateTimeField(default=datetime.datetime(2018, 9, 28, 7, 53, 52, 863720, tzinfo=utc))),
                ('modDate', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to='Documents.AppUser')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='Documents.AppUser')),
                ('members', models.ManyToManyField(blank=True, null=True, to='Documents.AppUser')),
            ],
        ),
    ]
