# Generated by Django 2.1.1 on 2018-09-29 02:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNum', models.IntegerField(editable=False, unique=True)),
                ('type', models.CharField(default='unknown', max_length=20)),
                ('createDate', models.DateTimeField(default=datetime.datetime(2018, 9, 29, 2, 7, 24, 233981, tzinfo=utc))),
                ('attachment', models.ManyToManyField(blank=True, related_name='DocAttachment', to='Documents.Documents')),
                ('children', models.ManyToManyField(blank=True, related_name='DocChildren', to='Documents.Documents')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DocCreator', to='Documents.AppUser')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 2, 7, 24, 232947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='Documents.AppUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectNumber',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DocProject', to='Documents.Project'),
        ),
    ]
