# Generated by Django 2.1.1 on 2018-09-29 07:12

import Documents.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20180929_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FilePathField(null=True, path=Documents.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 7, 12, 40, 267357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='docNum',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 7, 12, 40, 266314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
