# Generated by Django 2.1.1 on 2018-09-29 07:15

import Documents.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_auto_20180929_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 7, 15, 24, 314047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to=Documents.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 7, 15, 24, 312585, tzinfo=utc)),
        ),
    ]
