# Generated by Django 2.1.1 on 2018-10-18 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_auto_20180929_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locker', to='Documents.AppUser'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 35, 46, 848268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 35, 46, 847242, tzinfo=utc)),
        ),
    ]
